name: hana
description: Hana SDK for Dart
version: 0.0.1
homepage: https://dev.hana.ooo

environment:
  sdk: ">=2.14.4 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
